jobs:
  flow-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verificar Fluxo
        id: flow_guard
        uses: ./path/to/action  # ou owner/repo@version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Personalização opcional (se não passar, usa os defaults)
          production_branches: "main,master"
          staging_branches: "homol,staging"
          development_branches: "dev,develop"

      # EXEMPLO 1: Usando o pr-comment (agora desacoplado)
      - name: Comentar na PR
        uses: Malnati/pr-comment@v4.2.5
        if: always() # Executa mesmo se falhar
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          # Parseamos o JSON para passar valores (requer jq ou similar no runner)
          body_message: |
            Resultado da Análise de Fluxo:
            ${{ fromJson(steps.flow_guard.outputs.result_json).message }}
          footer_result: "Permitido: ${{ fromJson(steps.flow_guard.outputs.result_json).compliance.allowed }}"

      # EXEMPLO 2: Bloquear a PR se o fluxo estiver errado
      - name: Bloquear Merge
        if: ${{ fromJson(steps.flow_guard.outputs.result_json).compliance.allowed == false }}
        run: |
          echo "::error::${{ fromJson(steps.flow_guard.outputs.result_json).message }}"
          exit 1
